### PR TITLE
Our Team Update- Slok

### PR DESCRIPTION
**Pull request by sloker119**
- Added "Founders" and "Everyone That Got Us Here" titles
- changed nav bar hover color to GiveCard green because it was slightly off in color (don't know if it was supposed to be off in color , but it looked weird so I changed it). 

OurTeamsUpdate

### CODE REVIEW

**Comment by lurein** [comment]
@sloker119 I've got a few comments here, see below

**Comment by lurein** [comment]
1) Test this in mobile view, there's some weird stuff going on:
Screen Shot 2021-07-21 at 11 33 58 AM

compare this to the current GiveCard site - remember that you can use Chrome Developer Tools to look at mobile views

**Comment by lurein** [comment]
also on desktop view, could you center / re-align diksha and my sections in the founder part? they're a little unevenly spaced, could you space them in a way that looks good

**Comment by sloker119** [comment]
- fixed page width issue
- centered founders and everyone that got us here for clean look 
- fixed apply page title 
- added green button style to donate on the apply page because it was missing
OurTeamsUpdate2

**Comment by sloker119** [comment]
- also reformatted pictures a little so the bios are aligned

**Pull request closed without merging**
